# Generated by Django 3.2.1 on 2021-05-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='brth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
