# Generated by Django 3.2.2 on 2021-05-14 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='info',
            field=models.TextField(default=datetime.datetime(2021, 5, 14, 9, 46, 31, 616466, tzinfo=utc), verbose_name='Info'),
            preserve_default=False,
        ),
    ]
