# Generated by Django 3.2.2 on 2021-05-14 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 5, 14, 9, 59, 54, 438989, tzinfo=utc), upload_to='games/', verbose_name='Poster'),
            preserve_default=False,
        ),
    ]
